[build-system]
requires = ["hatchling ~= 1.27.0"]
build-backend = "hatchling.build"

[project]
name = "{{ name }}"
version = "0.1.0"
description = "AgentCore Runtime Application using Strands SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aws-opentelemetry-distro ~= 0.18.0",
    "bedrock-agentcore ~= 1.9.1",
    "botocore[crt] ~= 1.43.0",
    "mcp ~= 1.24.0",
    {{#if bedrockMantle}}"openai ~= 1.0.0",
    "aws-bedrock-token-generator ~= 1.0.0",
    {{/if}}{{#if (eq modelProvider "Anthropic")}}"strands-agents[anthropic] ~= 1.15.0",
    {{else}}{{#if (eq modelProvider "OpenAI")}}"strands-agents[openai] ~= 1.15.0",
    {{else}}{{#if (eq modelProvider "Gemini")}}"strands-agents[gemini] ~= 1.15.0",
    {{else}}{{#if (eq modelProvider "LiteLLM")}}"strands-agents[litellm] ~= 1.15.0",
    {{else}}"strands-agents ~= 1.15.0",
    {{/if}}{{/if}}{{/if}}{{/if}}
    {{#if (or hasBrowser hasCodeInterpreter)}}"strands-agents-tools ~= 0.1.0",
    {{/if}}{{#if hasBrowser}}"nest-asyncio ~= 1.5.0",
    "playwright ~= 1.42.0",
    {{/if}}{{#if hasGateway}}{{#if (includes gatewayAuthTypes "AWS_IAM")}}"mcp-proxy-for-aws ~= 1.1.0",
    {{/if}}{{/if}}
]

[tool.hatch.build.targets.wheel]
packages = ["."]
